#name: Deploy Infra

#on:
#  push:
#    branches:
#      - main

#jobs:
#  terraform:
#    runs-on: ubuntu-latest#

#    steps:
#      - uses: actions/checkout@v3

#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2

#      - name: Terraform Init
#        run: terraform -chdir=terraform init
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}#

#      - name: Terraform Apply
#        run: terraform -chdir=terraform apply -auto-approve
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
